blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/nicholasgriffintn/ui-doc/tree/main/docs
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/nicholasgriffintn/ui-doc/discussions
    about: Ask questions and discuss ideas
